INSERT INTO `address` (`street`, `city`, `country`, `zip_code`) VALUES
 ('Calle de prueba 1', 'Albacete', 'Spain', '12345'),
('Calle de prueba 2', 'Madrid', 'Germany', '67890'),
('Calle de prueba 3', 'Barcelona', 'France', '13579'),
('Calle de prueba 4', 'Valencia', 'Italy', '24680'),
('Calle de prueba 5', 'Sevilla', 'Netherlands', '86420'),
('Calle de prueba 6', 'Zaragoza', 'Portugal', '97531'),
('Calle de prueba 7', 'Málaga', 'Greece', '80246'),
('Calle de prueba 8', 'Murcia', 'Sweden', '62345'),
('Calle de prueba 9', 'Palma de Mallorca', 'Denmark', '71428'),
('Calle de prueba 10', 'Bilbao', 'Switzerland', '53179'),
('Calle de prueba 11', 'Alicante', 'Austria', '94620'),
('Calle de prueba 12', 'Córdoba', 'Belgium', '25783'),
('Calle de prueba 13', 'Valladolid', 'Norway', '36894'),
('Calle de prueba 14', 'Vigo', 'Ireland', '47925'),
('Calle de prueba 15', 'Gijón', 'Finland', '59013'),
('Calle de prueba 16', 'Huelva', 'Luxembourg', '60124'),
('Calle de prueba 17', 'A Coruña', 'United Kingdom', '71245'),
('Calle de prueba 18', 'Granada', 'Canada', '82356'),
('Calle de prueba 19', 'Toledo', 'United States', '93467'),
('Calle de prueba 20', 'Pamplona', 'Australia', '14578'),
('Calle de prueba 21', 'Santander', 'New Zealand', '25689');

INSERT INTO `user` (`id`, `name`, `password`, `username`, `address_street`) VALUES
(NULL, 'admin', 'admin', 'admin', 'Calle de prueba 1'),
(NULL, 'John Smith', 'password123', 'johnsmith', 'Calle de prueba 2'),
(NULL, 'Emma Johnson', 'abc123', 'emmajohnson', 'Calle de prueba 3'),
(NULL, 'Michael Williams', 'secret456', 'michaelwilliams', 'Calle de prueba 4'),
(NULL, 'Olivia Brown', 'myPass789', 'oliviabrown', 'Calle de prueba 5'),
(NULL, 'William Jones', 'qwerty987', 'williamjones', 'Calle de prueba 6'),
(NULL, 'Ava Taylor', 'p@ssw0rd', 'avataylor', 'Calle de prueba 7'),
(NULL, 'James Davis', 'pass1234', 'jamesdavis', 'Calle de prueba 8'),
(NULL, 'Isabella Miller', 'secure5678', 'isabellamiller', 'Calle de prueba 9'),
(NULL, 'Benjamin Wilson', 'testpass', 'benjaminwilson', 'Calle de prueba 10'),
(NULL, 'Sophia Moore', 'newpassword', 'sophiamoore', 'Calle de prueba 11'),
(NULL, 'Daniel Anderson', 'password1', 'danielanderson', 'Calle de prueba 12'),
(NULL, 'Mia Taylor', 'pass12345', 'miataylor', 'Calle de prueba 13'),
(NULL, 'Joseph Thomas', 'securepass', 'josephthomas', 'Calle de prueba 14'),
(NULL, 'Emily Martinez', 'test1234', 'emilymartinez', 'Calle de prueba 15'),
(NULL, 'David Robinson', 'mypassword', 'davidrobinson', 'Calle de prueba 16'),
(NULL, 'Charlotte Clark', 'newpass123', 'charlotteclark', 'Calle de prueba 17'),
(NULL, 'Samantha Lewis', 'testpass123', 'samanthalewis', 'Calle de prueba 18'),
(NULL, 'Andrew Lee', 'pass456', 'andrewlee', 'Calle de prueba 19'),
(NULL, 'Oliver Walker', 'password12345', 'oliverwalker', 'Calle de prueba 20'),
(NULL, 'Mia Harris', 'abcde', 'miaharris', 'Calle de prueba 21'),
(NULL, 'Liam Hall', 'password987', 'liamhall', 'Calle de prueba 2'),
(NULL, 'Ava Young', 'pass123abc', 'avayoung', 'Calle de prueba 3'),
(NULL, 'Noah Turner', 'securepass123', 'noahturner', 'Calle de prueba 4'),
(NULL, 'Emma Adams', 'mySecretPass', 'emmaadams', 'Calle de prueba 5'),
(NULL, 'Liam Hernandez', '12345678', 'liamhernandez', 'Calle de prueba 6'),
(NULL, 'Sophia Wright', 'password1234', 'sophiawright', 'Calle de prueba 7');

INSERT INTO `todo` (`id`, `completed`, `title`, `user_id`) VALUES
(NULL,true, 'Duis aute irure dolor', 10),
(NULL,true, 'Lorem ipsum dolor sit amet', 7),
(NULL,false, 'Consectetur adipiscing elit', 3),
(NULL,true, 'Sed do eiusmod tempor', 9),
(NULL,false, 'Incididunt ut labore et dolore', 5),
(NULL,true, 'Magna aliqua. Ut enim', 2),
(NULL,false, 'Ad minim veniam, quis', 8),
(NULL,true, 'Nostrud exercitation ullamco', 4),
(NULL,false, 'Laboris nisi ut aliquip', 6),
(NULL,true, 'Ex ea commodo consequat', 1),
(NULL,true, 'Duis aute irure dolor', 10),
(NULL, true, 'Dont judge a book by its cover', 20),
(NULL, true, 'Every cloud has a silver lining', 16),
(NULL, true, 'Fortune favors the bold', 13),
(NULL, true, 'Honesty is the best policy', 15),
(NULL, true, 'Laughter is the best medicine', 10),
(NULL, true, 'The early bird catches the worm', 1),
(NULL, false, 'The quick brown fox jumps over the lazy dog', 11),
(NULL, true, 'A picture is worth a thousand words', 1),
(NULL, false, 'Actions speak louder than words', 17),
(NULL, true, 'Beauty is in the eye of the beholder', 12),
(NULL, true, 'Every cloud has a silver lining', 16),
(NULL, true, 'Fortune favors the bold', 13),
(NULL, false, 'Honesty is the best policy', 15),
(NULL, false, 'Laughter is the best medicine', 10),
(NULL, true, 'The early bird catches the worm', 1),
(NULL, true, 'Practice makes perfect', 11),
(NULL, false, 'Variety is the spice of life', 19),
(NULL, true, 'Two heads are better than one', 17),
(NULL, false, 'When in Rome, do as the Romans do', 20),
(NULL, false, 'Better late than never', 16),
(NULL, true, 'The pen is mightier than the sword', 15),
(NULL, false, 'Actions speak louder than words', 1),
(NULL, false, 'A journey of a thousand miles begins with a single step', 18),
(NULL, true, 'Every dog has its day', 11),
(NULL, false, 'If the shoe fits, wear it', 14),
(NULL, true, 'Necessity is the mother of invention', 19),
(NULL, false, 'The early bird catches the worm', 11),
(NULL, true, 'Practice makes perfect', 1),
(NULL, true, 'Variety is the spice of life', 17),
(NULL, true, 'Two heads are better than one', 12),
(NULL, '', 'El titulo descriptivo de una tarea', '2');